services:
  traefik:
    image: traefik:latest
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
    command:  
     - "--providers.docker"
     - "--api.insecure=true"
     - "--providers.docker"
     - "--entrypoints.web.address=:8093"
     - "--log=true"
    ports:
      # http
      - "8080:8093"
      # ui: http://localhost:8090
      - "8090:8080" 

  # http://localhost:8080 via traefik
  mermaidlive:
    build:
      context: .
    environment:
      - TRAEFIK_SERVICES_URL=http://traefik:8080/api/http/services/mermaidlive%40docker
      - MML_CLUSTER_OBSERVABILITY_ENABLED=true
      - COUNTER_DIRECTORY=/appdata
    deploy:
      replicas: 3
    labels:
      - "traefik.http.routers.inventory-api-service.rule=PathPrefix(`/`)"
      - "traefik.http.services.mermaidlive.loadbalancer.server.port=8080"
      - "traefik.http.services.mermaidlive.loadBalancer.sticky.cookie"
