# fly.toml app configuration file generated for mermaidlive on 2024-06-16T13:52:31+02:00
#
# See https://fly.io/docs/reference/configuration/ for information about how to use this file.
#

app = 'mermaidlive'
primary_region = 'ams'

[build]

[env]
  COUTER_FILENAME = '/data/local.gcounter'
  GIN_MODE = 'release'
  RATE_LIMIT = '100-M'

[[mounts]]
  source = 'data'
  destination = '/data'
  initial_size = '1GB'

[http_service]
  internal_port = 8080
  force_https = true
  auto_stop_machines = true
  auto_start_machines = true
  min_machines_running = 0
  processes = ['app']

[[vm]]
  size = 'shared-cpu-1x'
