[build]
  command = "go run . -transpile && go build --tags=embed -v -o /run-app ."
  functions = "functions"
  publish = "site"
[build.environment]
  GO_VERSION = 1.22
  GO_IMPORT_PATH = "github.com/d-led/mermaidlive"
