// Generated by https://quicktype.io

export interface CatalogObject {
  id: string;
  name: string;
  data?: ObjectDetail;
}

export interface ObjectDetail {
  color?: string;
  capacity?: string;
  "capacity GB"?: number;
  price?: number;
  generation?: string;
  year?: number;
  "CPU model"?: string;
  "Hard disk size"?: string;
  "Strap Colour"?: string;
  "Case Size"?: string;
  Color?: string;
  Description?: string;
  Capacity?: string;
  "Screen size"?: number;
  Generation?: string;
  Price?: string;
}
